
version: '3.2'
services:
  web-tesis:
    entrypoint: yarn start
    environment:
      REACT_APP_API_BASE_URL: http://django:8080/api/
    hostname: web-tesis
    image: node:20
    #restart: unless-stopped
    volumes:
      - .:/App
      - ../Common:/Common
    working_dir: /App
